package com.kenai.javaatm;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pinpad.java
 *
 * Created on May 4, 2010, 6:46:38 PM
 */
/**
 *
 * @author hadj
 */
public class Keypad extends javax.swing.JPanel {

    /** Creates new form Pinpad */
    public Keypad() {
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "Keypad", "void", "void");
			initComponents();
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "Keypad", "void", "void");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
			ch.hesge.csim2.engine.TraceLogger
					.entering("com.kenai.javaatm", "Keypad#" + this.hashCode(),
							"com.kenai.javaatm", "Keypad#" + this.hashCode(),
							"initComponents", "void", "void");
			jButtonConfirm = new javax.swing.JButton();
			jButton0 = new javax.swing.JButton();
			jButtonClear = new javax.swing.JButton();
			jButton1 = new javax.swing.JButton();
			jButton2 = new javax.swing.JButton();
			jButton3 = new javax.swing.JButton();
			jButton4 = new javax.swing.JButton();
			jButton5 = new javax.swing.JButton();
			jButton6 = new javax.swing.JButton();
			jButton7 = new javax.swing.JButton();
			jButton8 = new javax.swing.JButton();
			jButton9 = new javax.swing.JButton();
			jTextFieldKeypad = new javax.swing.JTextField();
			setOpaque(false);
			setPreferredSize(new java.awt.Dimension(230, 160));
			setPreferredSize(new java.awt.Dimension(230, 260));
			jButtonConfirm.setText("Confirm");
			jButtonConfirm.setEnabled(false);
			jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButtonConfirmActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton0.setText("0");
			jButton0.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton0ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButtonClear.setText("Clear");
			jButtonClear.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButtonClearActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton1.setText("1");
			jButton1.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton1ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton2.setText("2");
			jButton2.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton2ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton3.setText("3");
			jButton3.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton3ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton4.setText("4");
			jButton4.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton4ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton5.setText("5");
			jButton5.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton5ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton6.setText("6");
			jButton6.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton6ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton7.setText("7");
			jButton7.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton7ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton8.setText("8");
			jButton8.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton8ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jButton9.setText("9");
			jButton9.addActionListener(new java.awt.event.ActionListener() {
			    public void actionPerformed(java.awt.event.ActionEvent evt) {
			        try {
						ch.hesge.csim2.engine.TraceLogger.entering(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
						jButton9ActionPerformed(evt);
					} finally {
						ch.hesge.csim2.engine.TraceLogger.exiting(
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(),
								"com.kenai.javaatm",
								"Keypad$java.awt.event.ActionListener#"
										+ this.hashCode(), "actionPerformed",
								"java.awt.event.ActionEvent evt", "void");
					}
			    }
			});
			jTextFieldKeypad.setBackground(java.awt.Color.gray);
			jTextFieldKeypad.setEditable(false);
			jTextFieldKeypad.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
			jTextFieldKeypad.setForeground(new java.awt.Color(165, 247, 172));
			jTextFieldKeypad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
			this.setLayout(layout);
			layout.setHorizontalGroup(
			    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
			        .addContainerGap()
			        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			            .addComponent(jTextFieldKeypad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
			            .addGroup(layout.createSequentialGroup()
			                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButtonConfirm))
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
			                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
			                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
			                        .addComponent(jButtonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
			                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
			                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
			        .addContainerGap())
			);
			layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton0, jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonClear, jButtonConfirm});
			layout.setVerticalGroup(
			    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
			        .addComponent(jTextFieldKeypad)
			        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
			        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			            .addGroup(layout.createSequentialGroup()
			                .addComponent(jButton6)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButton3)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButtonClear))
			            .addGroup(layout.createSequentialGroup()
			                .addComponent(jButton5)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButton2)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButton0))
			            .addGroup(layout.createSequentialGroup()
			                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton7)
			                    .addComponent(jButton8)
			                    .addComponent(jButton9))
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButton4)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButton1)
			                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                .addComponent(jButtonConfirm)))
			        .addContainerGap())
			);
			layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton0, jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonClear, jButtonConfirm});
		} finally {
			ch.hesge.csim2.engine.TraceLogger
					.exiting("com.kenai.javaatm", "Keypad#" + this.hashCode(),
							"com.kenai.javaatm", "Keypad#" + this.hashCode(),
							"initComponents", "void", "void");
		}

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButtonConfirmActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			cinfirmButtonClicked = true;
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButtonConfirmActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton0ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "0");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton0ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButtonClearActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText("");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButtonClearActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton1ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "1");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton1ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton2ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "2");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton2ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton3ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "3");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton3ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton4ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "4");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton4ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton5ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "5");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton5ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton6ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "6");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton6ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton7ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "7");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton7ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton8ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "8");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton8ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton9ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
			jTextFieldKeypad.setText(jTextFieldKeypad.getText() + "9");
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "jButton9ActionPerformed",
					"java.awt.event.ActionEvent evt", "void");
		}
    }//GEN-LAST:event_jButton9ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JTextField jTextFieldKeypad;
    // End of variables declaration//GEN-END:variables
    boolean cinfirmButtonClicked = false;

    // return an integer value entered by user
    public int getInput() {
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "getInput", "void", "int");
			int ouput;
			jButtonConfirm.setEnabled(true);
			while (!cinfirmButtonClicked) {
			    System.out.print("");
			}
			cinfirmButtonClicked = false;
			jButtonConfirm.setEnabled(false);
			try {
			    ouput = Integer.valueOf(jTextFieldKeypad.getText());
			} catch (NumberFormatException e) {
			    ouput = -1;
			} // we assume that user enters an integer
			jTextFieldKeypad.setText("");
			return ouput;
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Keypad#" + this.hashCode(), "com.kenai.javaatm", "Keypad#"
							+ this.hashCode(), "getInput", "void", "int");
		}
    } // end method getInput
}
