package com.kenai.javaatm;
/*

 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiplayScreen.java
 *
 * Created on May 5, 2010, 2:47:33 PM
 */

/**
 *
 * @author hadj
 */
public class Screen extends javax.swing.JPanel {

    /** Creates new form DiplayScreen */
    public Screen() {
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
							+ this.hashCode(), "Screen", "void", "void");
			initComponents();
			initComponentsExtra();
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
							+ this.hashCode(), "Screen", "void", "void");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        try {
			ch.hesge.csim2.engine.TraceLogger
					.entering("com.kenai.javaatm", "Screen#" + this.hashCode(),
							"com.kenai.javaatm", "Screen#" + this.hashCode(),
							"initComponents", "void", "void");
			jLabelImageScreen = new javax.swing.JLabel();
			jScrollPaneScreen = new javax.swing.JScrollPane();
			screen = new javax.swing.JTextArea();
			setPreferredSize(new java.awt.Dimension(605, 398));
			setLayout(null);
			jLabelImageScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
			jLabelImageScreen.setLabelFor(this);
			add(jLabelImageScreen);
			jLabelImageScreen.setBounds(290, 170, 160, 210);
			this.setOpaque(false);
			screen.setBackground(java.awt.Color.GRAY);
			screen.setEditable(false);
			screen.setFont(new java.awt.Font("Nimbus Sans L", 0, 28)); // NOI18N
			screen.setForeground(new java.awt.Color(170, 253, 171));
			screen.setMargin(new java.awt.Insets(10, 20, 10, 20));
			screen.setColumns(20);
			screen.setRows(5);
			jScrollPaneScreen.setViewportView(screen);
			add(jScrollPaneScreen);
			jScrollPaneScreen.setBounds(0, 0, 605, 398);
		} finally {
			ch.hesge.csim2.engine.TraceLogger
					.exiting("com.kenai.javaatm", "Screen#" + this.hashCode(),
							"com.kenai.javaatm", "Screen#" + this.hashCode(),
							"initComponents", "void", "void");
		}
    }// </editor-fold>

    public void initComponentsExtra()
    {
        try {
			ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
					"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
							+ this.hashCode(), "initComponentsExtra", "void",
					"void");
			jLabelImageScreen.setVisible(false);
		} finally {
			ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
					"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
							+ this.hashCode(), "initComponentsExtra", "void",
					"void");
		}
    }
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabelImageScreen;
    private javax.swing.JScrollPane jScrollPaneScreen;
    private javax.swing.JTextArea screen;
    // End of variables declaration


   // displays a message without a carriage return
   public void displayMessage( String message )
   {
       
try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayMessage", "String message",
				"void");
		screen.append(message);
		  //System.out.print( message );
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayMessage", "String message",
				"void");
	}
   } // end method displayMessage

   // display a message with a carriage return
   public void displayMessageLine( String message )
   {
       
try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayMessageLine",
				"String message", "void");
		screen.append(message+"\n");
		  //System.out.println( message );
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayMessageLine",
				"String message", "void");
	}
   } // end method displayMessageLine

   public void clearMessageScreen()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger
				.entering("com.kenai.javaatm", "Screen#" + this.hashCode(),
						"com.kenai.javaatm", "Screen#" + this.hashCode(),
						"clearMessageScreen", "void", "void");
		screen.setText("");
	} finally {
		ch.hesge.csim2.engine.TraceLogger
				.exiting("com.kenai.javaatm", "Screen#" + this.hashCode(),
						"com.kenai.javaatm", "Screen#" + this.hashCode(),
						"clearMessageScreen", "void", "void");
	}

   } // end method displayMessageLine

   public void diplayInsertCardImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayInsertCardImage", "void",
				"void");
		jLabelImageScreen.repaint();
		jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kenai/javaatm/icons/insertCardScreen.png")));
		jLabelImageScreen.setVisible(true);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayInsertCardImage", "void",
				"void");
	}

   }

   public void clearInsertCardImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearInsertCardImage", "void",
				"void");
		jLabelImageScreen.setVisible(false);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearInsertCardImage", "void",
				"void");
	}
      
   }
      
   public void diplayRemoveCardImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayRemoveCardImage", "void",
				"void");
		jLabelImageScreen.repaint();
		jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kenai/javaatm/icons/removeCardScreen.png")));
		jLabelImageScreen.setVisible(true);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayRemoveCardImage", "void",
				"void");
	}

   }

   public void clearRemoveCardImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearRemoveCardImage", "void",
				"void");
		jLabelImageScreen.setVisible(false);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearRemoveCardImage", "void",
				"void");
	}
   }

   public void diplayPutEnvelopeImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayPutEnvelopeImage", "void",
				"void");
		jLabelImageScreen.repaint();
		jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kenai/javaatm/icons/DepositScreen.png")));
		jLabelImageScreen.setVisible(true);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayPutEnvelopeImage", "void",
				"void");
	}
   }

   public void clearPutEnvelopeImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearPutEnvelopeImage", "void",
				"void");
		jLabelImageScreen.setVisible(false);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearPutEnvelopeImage", "void",
				"void");
	}
   }

   public void diplayTakeMoneyImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayTakeMoneyImage", "void",
				"void");
		jLabelImageScreen.repaint();
		jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kenai/javaatm/icons/CashScreen.png")));
		jLabelImageScreen.setVisible(true);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "diplayTakeMoneyImage", "void",
				"void");
	}
   }

   public void clearTakeMoneyImage()
   {
       try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearTakeMoneyImage", "void",
				"void");
		jLabelImageScreen.setVisible(false);
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "clearTakeMoneyImage", "void",
				"void");
	}
   }



   // display a dollar amount
   public void displayDollarAmount( double amount )
   {
    
try {
		ch.hesge.csim2.engine.TraceLogger.entering("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayDollarAmount",
				"double amount", "void");
		screen.append("$ "+amount);
		   //System.out.printf( "$%,.2f", amount );
	} finally {
		ch.hesge.csim2.engine.TraceLogger.exiting("com.kenai.javaatm",
				"Screen#" + this.hashCode(), "com.kenai.javaatm", "Screen#"
						+ this.hashCode(), "displayDollarAmount",
				"double amount", "void");
	}
   } // end method displayDollarAmount
}

/**************************************************************************
 *  2009-2010 by SENOUCI hadj.
 *  Email: senoucihs@gmail.com
 *  this code is free which mean
 *  you can re-utilize it as you want
 *************************************************************************/