package ch.hesge.csim2.ui.comp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import ch.hesge.csim2.ui.views.ConsoleView2;

@SuppressWarnings("serial")
public class ConsolePopup extends JPopupMenu implements ActionListener {

	// Private attribute
	private ConsoleView2 owner;
	
	private JMenuItem mnuClear;

	/**
	 * Default constructor
	 */
	public ConsolePopup(ConsoleView2 owner) {

		this.owner = owner;

		mnuClear = new JMenuItem("Clear");
		mnuClear.addActionListener(this);
		add(mnuClear);
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == mnuClear) {
			owner.clearLogConsole();
		}
	}
}
