package ch.hesge.csim2.ui.comp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import ch.hesge.csim2.core.logic.ApplicationLogic;
import ch.hesge.csim2.core.model.IEngine;
import ch.hesge.csim2.ui.views.ActionHandler;

@SuppressWarnings("serial")
public class EnginePopup extends JPopupMenu implements ActionListener {

	// Private attributes
	private IEngine engine;
	private ActionHandler actionHandler;
	private JMenuItem mnuStart;
	private JMenuItem mnuStop;

	/**
	 * Default constructor
	 */
	public EnginePopup(ActionHandler actionHandler) {

		this.actionHandler = actionHandler;
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {

		mnuStart = new JMenuItem("Start the engine");
		mnuStart.addActionListener(this);
		add(mnuStart);

		mnuStop = new JMenuItem("Stop the engine");
		mnuStop.addActionListener(this);
		add(mnuStop);
	}

	/**
	 * Return the engine this popup is linked to.
	 * 
	 * @return the engine
	 */
	public IEngine getEngine() {
		return engine;
	}

	/**
	 * Sets the engine this popup is linked to.
	 * 
	 * @param engine
	 *            the engine to set
	 */
	public void setEngine(IEngine engine) {

		this.engine = engine;
		
		if (engine != null) {
			
			if (ApplicationLogic.isEngineRunning(engine)) {
				mnuStart.setEnabled(false);
				mnuStop.setEnabled(true);
			}
			else {
				mnuStart.setEnabled(true);
				mnuStop.setEnabled(false);
			}
		}
		else {
			mnuStart.setEnabled(false);
			mnuStop.setEnabled(false);
		}
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == mnuStart) {
			actionHandler.startEngine(engine);
		}
		else if (e.getSource() == mnuStop) {
			actionHandler.stopEngine(engine);
		}
	}
}
