package ch.hesge.csim2.ui.comp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import javax.swing.SwingUtilities;

import ch.hesge.csim2.core.model.Ontology;
import ch.hesge.csim2.ui.views.MainView;

@SuppressWarnings("serial")
public class OntologyPopup extends JPopupMenu implements ActionListener {

	// Private attributes
	private Ontology ontology;
	private JMenuItem mnuNew;
	private JMenuItem mnuOpen;
	private JMenuItem mnuDelete;

	/**
	 * Default constructor
	 */
	public OntologyPopup() {
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {
		
		mnuNew = new JMenuItem("Create an ontology");
		mnuNew.addActionListener(this);
		add(mnuNew);

		mnuDelete = new JMenuItem("Delete the ontology");
		mnuDelete.addActionListener(this);
		add(mnuDelete);

		add(new JSeparator());

		mnuOpen = new JMenuItem("Open the ontology");
		mnuOpen.addActionListener(this);
		add(mnuOpen);
	}

	/**
	 * Clear menu state
	 */
	public void clearMenuState() {	
		mnuNew.setEnabled(false);
		mnuOpen.setEnabled(false);
		mnuDelete.setEnabled(false);
	}
	
	/**
	 * Enable/disable new menu
	 */
	public void setCreateMenuState(boolean state) {
		mnuNew.setEnabled(state);
	}

	/**
	 * Enable/disable edit menu
	 */
	public void setOpenMenuState(boolean state) {
		mnuOpen.setEnabled(state);
	}

	/**
	 * Enable/disable delete menu
	 */
	public void setDeleteMenuState(boolean state) {
		mnuDelete.setEnabled(state);
	}

	/**
	 * @return the ontology
	 */
	public Ontology getOntology() {
		return ontology;
	}

	/**
	 * @param ontology
	 *            the ontology to set
	 */
	public void setOntology(Ontology ontology) {
		this.ontology = ontology;
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		MainView mainView = (MainView) SwingUtilities.getAncestorOfClass(MainView.class, this.getInvoker());
		
		if (e.getSource() == mnuNew) {
			JOptionPane.showMessageDialog(mainView, "This feature is not yet implemented !", "Warning", JOptionPane.WARNING_MESSAGE);
		}
		else if (e.getSource() == mnuOpen) {
			mainView.showOntology(ontology);
		}
		else if (e.getSource() == mnuDelete) {
			JOptionPane.showMessageDialog(mainView, "This feature is not yet implemented !", "Warning", JOptionPane.WARNING_MESSAGE);
		}
	}

}
