package ch.hesge.csim2.ui.comp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

import ch.hesge.csim2.core.model.Project;
import ch.hesge.csim2.ui.views.MainView;

@SuppressWarnings("serial")
public class ProjectPopup extends JPopupMenu implements ActionListener {

	// Private attributes
	private Project project;
	private JMenuItem mnuRename;
	private JMenuItem mnuDelete;

	/**
	 * Default constructor
	 */
	public ProjectPopup() {
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {

		mnuRename = new JMenuItem("Rename the project");
		mnuRename.addActionListener(this);
		add(mnuRename);

		mnuDelete = new JMenuItem("Delete the project");
		mnuDelete.addActionListener(this);
		add(mnuDelete);
	}

	/**
	 * Return the project concerned by this popup.
	 * 
	 * @return the project
	 */
	public Project getProject() {
		return project;
	}

	/**
	 * Sets the project concerned by this popup.
	 * 
	 * @param project
	 *            the project to set
	 */
	public void setProject(Project project) {
		this.project = project;
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		MainView mainView = (MainView) SwingUtilities.getAncestorOfClass(MainView.class, this.getInvoker());

		if (e.getSource() == mnuRename) {
			mainView.renameProject(project);
		}
		else if (e.getSource() == mnuDelete) {
			mainView.deleteProject(project);
		}
	}

}
