package ch.hesge.csim2.ui.comp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;

import ch.hesge.csim2.core.model.Scenario;
import ch.hesge.csim2.ui.views.ActionHandler;

@SuppressWarnings("serial")
public class ScenarioPopup extends JPopupMenu implements ActionListener {

	// Private attributes
	private Scenario scenario;
	private ActionHandler actionHandler;
	private JMenuItem mnuNew;
	private JMenuItem mnuRename;
	private JMenuItem mnuOpen;
	private JMenuItem mnuStart;
	private JMenuItem mnuStop;
	private JMenuItem mnuDelete;

	/**
	 * Default constructor
	 */
	public ScenarioPopup(ActionHandler actionHandler) {
		
		this.actionHandler = actionHandler;
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {

		mnuNew = new JMenuItem("New Scenario");
		mnuNew.addActionListener(this);
		add(mnuNew);

		mnuRename = new JMenuItem("Rename");
		mnuRename.addActionListener(this);
		add(mnuRename);

		mnuDelete = new JMenuItem("Delete");
		mnuDelete.addActionListener(this);
		add(mnuDelete);

		add(new JSeparator());

		mnuOpen = new JMenuItem("Open");
		mnuOpen.addActionListener(this);
		add(mnuOpen);

		mnuStart = new JMenuItem("Start");
		mnuStart.addActionListener(this);
		add(mnuStart);

		mnuStop = new JMenuItem("Stop");
		mnuStop.addActionListener(this);
		add(mnuStop);
	}

	/**
	 * Return the scenario concerned by this popup.
	 * 
	 * @return the scenario
	 */
	public Scenario getScenario() {
		return scenario;
	}

	/**
	 * Sets the scenario concerned by this popup.
	 * 
	 * @param scenario
	 *            the scenario to set
	 */
	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	/**
	 * Clear menu state
	 */
	public void clearMenuState() {
		
		mnuNew.setEnabled(false);
		mnuRename.setEnabled(false);
		mnuDelete.setEnabled(false);
		mnuOpen.setEnabled(false);
		mnuStart.setEnabled(false);
		mnuStop.setEnabled(false);
	}
	
	/**
	 * Enable/disable new menu
	 */
	public void setCreateMenuState(boolean state) {
		mnuNew.setEnabled(state);
	}

	/**
	 * Enable/disable rename menu
	 */
	public void setRenameMenuState(boolean state) {
		mnuRename.setEnabled(state);
	}

	/**
	 * Enable/disable delete menu
	 */
	public void setDeleteMenuState(boolean state) {
		mnuDelete.setEnabled(state);
	}

	/**
	 * Enable/disable edit menu
	 */
	public void setOpenMenuState(boolean state) {
		mnuOpen.setEnabled(state);
	}

	/**
	 * Enable/disable start menu
	 */
	public void setStartMenuState(boolean state) {
		mnuStart.setEnabled(state);
	}

	/**
	 * Enable/disable stop menu
	 */
	public void setStopMenuState(boolean state) {
		mnuStop.setEnabled(state);
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == mnuNew) {
			actionHandler.createNewScenario();
		}
		else if (e.getSource() == mnuRename) {
			actionHandler.renameScenario(scenario);
		}
		else if (e.getSource() == mnuDelete) {
			actionHandler.deleteScenario(scenario);
		}
		else if (e.getSource() == mnuOpen) {
			actionHandler.showScenario(scenario);
		}
		else if (e.getSource() == mnuStart) {
			actionHandler.startScenario(scenario);
		}
		else if (e.getSource() == mnuStop) {
			actionHandler.stopScenario(scenario);
		}
	}
}
