package ch.hesge.csim2.ui.comp;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import ch.hesge.csim2.core.model.Trace;
import ch.hesge.csim2.core.utils.StringUtils;

@SuppressWarnings("serial")
public class TraceTable extends JTable implements ActionListener {

	// Private attributes
	private List<Trace> traces;
	private SourceMethodPopup contextMenu;
	private ListSelectionListener doubleClickListener;

	/**
	 * Default constructor
	 */
	public TraceTable() {
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {

		setRowSelectionAllowed(true);
		setGridColor(Color.LIGHT_GRAY);
		setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

		// Create a context menu
		contextMenu = new SourceMethodPopup(this);
		contextMenu.addActionListener(this);

		initModel();
		initListeners();
		initRenderer();
	}

	/**
	 * Initialize component inner listeners
	 */
	private void initListeners() {

		// Listen to single or double click
		addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				
				// Handle right-click
				if (SwingUtilities.isRightMouseButton(e)) {
					
					// Select row under the mouse
					int clickedRow = rowAtPoint(e.getPoint());
					setRowSelectionInterval(clickedRow,  clickedRow);

					// Show context menu
					contextMenu.show(e.getComponent(), e.getX(), e.getY());
					
					e.consume();										
				}
				else {
					
					if (e.getClickCount() == 2 && doubleClickListener != null) {
						doubleClickListener.valueChanged(new ListSelectionEvent(this, getSelectedRow(), getSelectedRow(), false));
					}
				}
			}
		});
	}

	/**
	 * Initialize the component's model
	 */
	private void initModel() {

		setModel(new DefaultTableModel() {

			@Override
			public int getColumnCount() {
				return 3;
			}

			@Override
			public String getColumnName(int col) {

				switch (col) {
					case 0:
						return "Class";
					case 1:
						return "Method";
					case 2:
						return "Level";
				}

				return null;
			}

			@Override
			public int getRowCount() {
				if (traces == null)
					return 0;
				return traces.size();
			}

			@Override
			public boolean isCellEditable(int row, int col) {
				return false;
			}

			@Override
			public Object getValueAt(int row, int col) {

				switch (col) {
					case 0:
						return traces.get(row).getStaticClass();
					case 1:
						Trace trace = traces.get(row);
						String identation = StringUtils.repeat("   ", (int) trace.getLevel());
						return identation + traces.get(row).getSignature();
					case 2:
						return traces.get(row).getLevel();
				}

				return null;
			}
		});
	}

	/**
	 * Initialize the table renderer
	 */
	private void initRenderer() {

		// Adjust column size
		TableColumnModel columnModel = getColumnModel();
		columnModel.getColumn(0).setMaxWidth(80);
		columnModel.getColumn(0).setMinWidth(80);
	}

	/**
	 * Sets the list this table should display.
	 * 
	 * @param traces
	 */
	public void setTraces(List<Trace> traces) {
		this.traces = traces;
		initModel();
		repaint();
	}

	/**
	 * Return the current selection
	 * 
	 * @return
	 *         a trace object
	 */
	public Trace getSelectedValue() {

		int row = getSelectedRow();

		if (row > -1) {
			return traces.get(row);
		}

		return null;
	}

	/**
	 * Add an double-click listener.
	 * 
	 * @param a instance of listselectionlistener
	 */
	public void addDoubleClickListener(ListSelectionListener listener) {
		this.doubleClickListener = listener;
	}

	/**
	 * Handle action generated by context menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getActionCommand().equals("OPEN_FILE")) {
			if (doubleClickListener != null) {
				doubleClickListener.valueChanged(new ListSelectionEvent(this, getSelectedRow(), getSelectedRow(), false));
			}
		}
	}
}
