package ch.hesge.csim2.ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

import ch.hesge.csim2.ui.model.ApplicationManager;
import ch.hesge.csim2.ui.utils.SwingUtils;

@SuppressWarnings("serial")
public class AboutDialog extends JDialog implements ActionListener {

	// Private attributes
	JButton btnOK;
	
	/**
	 * Create the dialog with owner.
	 */
	public AboutDialog(Window parent) {
		super(parent);
		initComponents();
	}

	/**
	 * Initialize the view components
	 */
	private void initComponents() {

		// Dialog configuration
		setTitle("About");
		setBounds(0, 0, 470, 320);
		setLocationRelativeTo(getParent());
		setModalityType(ModalityType.APPLICATION_MODAL);
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		// Create layout structure
		getContentPane().setLayout(new BorderLayout());
		JPanel btnPane = new JPanel();
		FlowLayout flowLayout = (FlowLayout) btnPane.getLayout();
		flowLayout.setAlignment(FlowLayout.RIGHT);
		getContentPane().add(btnPane, BorderLayout.SOUTH);

		// Initialize button pane
		btnOK = new JButton("OK");
		btnOK.setPreferredSize(new Dimension(100, 25));
		btnOK.addActionListener(this);
		btnPane.add(btnOK);
		
		JPanel textPanel = new JPanel();
		getContentPane().add(textPanel, BorderLayout.CENTER);
		textPanel.setLayout(null);
		
		JLabel titleLabel = new JLabel("CSIM2 Environment");
		titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
		titleLabel.setFont(new Font("Arial", Font.PLAIN, 40));
		titleLabel.setBounds(10, 46, 450, 47);
		textPanel.add(titleLabel);
		
		JLabel versionLabel = new JLabel("Version: " + ApplicationManager.UNIQUE_INSTANCE.getApplication().getVersion());
		versionLabel.setHorizontalAlignment(SwingConstants.CENTER);
		versionLabel.setFont(new Font("Arial", Font.PLAIN, 20));
		versionLabel.setBounds(10, 104, 450, 81);
		textPanel.add(versionLabel);
		
		JLabel copyrightLabel = new JLabel("Copyright \u00A9 HEG Geneva, Switzerland,  2011-2015");
		copyrightLabel.setVerticalAlignment(SwingConstants.BOTTOM);
		copyrightLabel.setHorizontalAlignment(SwingConstants.CENTER);
		copyrightLabel.setFont(new Font("Arial", Font.PLAIN, 14));
		copyrightLabel.setBounds(10, 225, 450, 17);
		textPanel.add(copyrightLabel);
		
		initListeners();
	}

	/**
	 * Initialize component listeners
	 */
	private void initListeners() {
		
		// Replace default ENTER action
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ESCAPE, "ENTER", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				AboutDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});

		// Replace default ESCAPE action
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ESCAPE, "ESCAPE", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				AboutDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});
	}
	
	/**
	 * Handle action generated by the view.
	 */
	public void actionPerformed(ActionEvent e) {
		this.setVisible(false);
	}
}
