package ch.hesge.csim2.ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

import ch.hesge.csim2.core.model.Concept;
import ch.hesge.csim2.ui.comp.ConceptAttributesTable;
import ch.hesge.csim2.ui.comp.ConceptClassesTable;
import ch.hesge.csim2.ui.utils.SwingUtils;

@SuppressWarnings("serial")
public class ConceptPropertiesDialog extends JDialog implements ActionListener {
	
	// Private attributes
	private Concept concept;
	private ConceptAttributesTable attributesTable;
	private ConceptClassesTable classesTable;
	private JButton btnOK;

	/**
	 * Create the dialog with owner.
	 */
	public ConceptPropertiesDialog(Window parent, Concept concept) {
		super(parent);	
		this.concept = concept;
		initComponents();
	}

	/**
	 * Initialize the view components
	 */
	private void initComponents() {

		// Dialog configuration
		setTitle("Detail");
		setBounds(0, 0, 473, 481);
		setLocationRelativeTo(getParent());
		setModalityType(ModalityType.APPLICATION_MODAL);
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		
		// Initialize main panel
		JPanel mainPanel = new JPanel();
		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(mainPanel, BorderLayout.CENTER);
		mainPanel.setLayout(new BorderLayout(0, 0));
		
		// Initialize title panel
		JPanel titlePanel = new JPanel();
		FlowLayout flowTitleLayout = (FlowLayout) titlePanel.getLayout();
		flowTitleLayout.setVgap(10);
		flowTitleLayout.setHgap(10);
		flowTitleLayout.setAlignment(FlowLayout.LEFT);
		mainPanel.add(titlePanel, BorderLayout.NORTH);		
		titlePanel.add(new JLabel("Concept:"));
		titlePanel.add(new JLabel(concept.getName()));
		
		// Initialize split panel
		JSplitPane splitPane = new JSplitPane();
		splitPane.setResizeWeight(0.8);
		splitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);
		mainPanel.add(splitPane, BorderLayout.CENTER);

		// Initialize button panel
		JPanel btnPane = new JPanel();
		FlowLayout flowBtnLayout = (FlowLayout) btnPane.getLayout();
		flowBtnLayout.setAlignment(FlowLayout.RIGHT);
		getContentPane().add(btnPane, BorderLayout.SOUTH);
		
		// Initialize attribute panel
		JPanel attributesPanel = new JPanel();
		splitPane.setLeftComponent(attributesPanel);
		attributesPanel.setBorder(new TitledBorder(null, "Attributes", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		attributesPanel.setLayout(new BorderLayout(0, 0));	
		
		// Initialize classes panel
		JPanel classesPanel = new JPanel();
		splitPane.setRightComponent(classesPanel);
		classesPanel.setBorder(new TitledBorder(null, "Classes", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		classesPanel.setLayout(new BorderLayout(0, 0));		

		// Initialize attribute table
		attributesTable = new ConceptAttributesTable(concept.getAttributes());
		JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setViewportView(attributesTable);
		attributesPanel.add(scrollPane1, BorderLayout.CENTER);
		
		// Initialize classes table
		classesTable = new ConceptClassesTable(concept.getClasses());
		JScrollPane scrollPane2 = new JScrollPane();
		scrollPane2.setViewportView(classesTable);
		classesPanel.add(scrollPane2, BorderLayout.CENTER);

		// Initialize button pane
		btnOK = new JButton("OK");
		btnOK.setPreferredSize(new Dimension(100, 25));
		btnOK.addActionListener(this);
		btnPane.add(btnOK);

		initListeners();
	}

	/**
	 * Initialize component listeners
	 */
	private void initListeners() {
		
		// Replace default ENTER action
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ESCAPE, "ENTER", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ConceptPropertiesDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});

		// Replace default ESCAPE action
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ESCAPE, "ESCAPE", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ConceptPropertiesDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});
	}
	
	/**
	 * Handle action generated by the view.
	 */
	public void actionPerformed(ActionEvent e) {
		this.setVisible(false);
	}
}
