package ch.hesge.csim2.ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;

import ch.hesge.csim2.core.model.Project;
import ch.hesge.csim2.ui.model.ApplicationManager;
import ch.hesge.csim2.ui.table.ProjectTable;
import ch.hesge.csim2.ui.utils.SimpleAction;
import ch.hesge.csim2.ui.utils.SwingUtils;

@SuppressWarnings("serial")
public class SelectProjectDialog extends JDialog implements ActionListener {

	// Private attributes
	private Project project;
	private ApplicationManager appManager;
	private ProjectTable projectTable;
	private JButton btnOK;
	private JButton btnCancel;
	private boolean dialogResult;

	/**
	 * Create the dialog with owner.
	 */
	public SelectProjectDialog(Window parent) {
		super(parent);
		this.appManager = ApplicationManager.UNIQUE_INSTANCE;
		initComponents();
	}

	/**
	 * Initialize the view components
	 */
	private void initComponents() {

		// Dialog configuration
		setTitle("New Project");
		setBounds(0, 0, 220, 245);
		setLocationRelativeTo(getParent());
		setModalityType(ModalityType.APPLICATION_MODAL);
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		// Create layout structure
		getContentPane().setLayout(new BorderLayout());
		JPanel mainPane = new JPanel();
		getContentPane().add(mainPane, BorderLayout.CENTER);
		mainPane.setLayout(new BorderLayout(0, 0));
		JPanel btnPane = new JPanel();
		FlowLayout flowLayout = (FlowLayout) btnPane.getLayout();
		flowLayout.setAlignment(FlowLayout.RIGHT);
		getContentPane().add(btnPane, BorderLayout.SOUTH);

		// Initialize project list
		projectTable = new ProjectTable();
		projectTable.setFillsViewportHeight(true);
		projectTable.setBackground(Color.WHITE);
		JScrollPane scrollbar = new JScrollPane();
		scrollbar.setViewportView(projectTable);
		mainPane.add(scrollbar, BorderLayout.CENTER);

		// Initialize ok button
		btnOK = new JButton("OK");
		btnOK.setPreferredSize(new Dimension(100, 25));
		btnOK.addActionListener(this);
		btnPane.add(btnOK);

		// Initialize cancel button
		btnCancel = new JButton("Cancel");
		btnCancel.setPreferredSize(new Dimension(100, 25));
		btnCancel.addActionListener(this);
		btnPane.add(btnCancel);

		initListeners();
	}

	/**
	 * Initialize component listeners
	 */
	private void initListeners() {

		// Initialize the view when visible
		SwingUtils.onComponentVisible(this.getRootPane(), new SimpleAction<Object>() {
			@Override
			public void run(Object o) {
				initView();
			}
		});

		// Listen to attribute selection
		SwingUtils.onTableDoubleClick(projectTable, new SimpleAction<MouseEvent>() {
			@Override
			public void run(MouseEvent e) {
				SelectProjectDialog.this.actionPerformed(new ActionEvent(btnOK, ActionEvent.ACTION_PERFORMED, null));
			}
		});

		// Detect ENTER key
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ENTER, "ENTER", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				SelectProjectDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});

		// Detect ESC key
		SwingUtils.setInputKeyAction(this.getRootPane(), KeyEvent.VK_ESCAPE, "ESCAPE", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				SelectProjectDialog.this.actionPerformed(new ActionEvent(btnCancel, e.getID(), null));
			}
		});
		
		// Detect ENTER key in project table
		SwingUtils.setInputKeyAction(projectTable, KeyEvent.VK_ENTER, "PROJECT_ENTER", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				SelectProjectDialog.this.actionPerformed(new ActionEvent(btnOK, e.getID(), null));
			}
		});
	}

	/**
	 * Initialize the view and its components.
	 */
	private void initView() {

		// Retrieve project list
		List<Project> projects = appManager.getProjects();

		// Initialize the project list
		projectTable.setProjects(projects);
	}

	/**
	 * Return dialog result.
	 * true = user clicked on OK
	 * false = use clicked on Cancel or ESC
	 * 
	 * @return the dialogResult
	 */
	public boolean getDialogResult() {
		return dialogResult;
	}

	/**
	 * Return the selected project
	 * @return
	 *         the project
	 */
	public Project getProject() {
		return project;
	}
	
	/**
	 * Handle action generated by the view.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == btnOK) {			
			project = projectTable.getSelectedObject();
			dialogResult = true;
			this.setVisible(false);
		}
		else if (e.getSource() == btnCancel) {
			dialogResult = false;
			this.setVisible(false);
		}
	}
}
