package ch.hesge.csim2.ui.popup;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import ch.hesge.csim2.ui.model.ApplicationManager;

@SuppressWarnings("serial")
public class ConsolePopup extends JPopupMenu implements ActionListener {

	// Private attribute
	private JMenuItem mnuClear;
	private ApplicationManager appManager;

	/**
	 * Default constructor
	 */
	public ConsolePopup() {
		appManager = ApplicationManager.UNIQUE_INSTANCE;
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {
		
		mnuClear = new JMenuItem("Clear console");
		mnuClear.addActionListener(this);
		add(mnuClear);
		
	}
	
	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == mnuClear) {
			appManager.clearConsole();
		}
	}
}
