package ch.hesge.csim2.ui.popup;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import ch.hesge.csim2.core.model.ScenarioStep;
import ch.hesge.csim2.ui.model.ApplicationManager;

@SuppressWarnings("serial")
public class ScenarioStepPopup extends JPopupMenu implements ActionListener {

	// Private attributes
	private ScenarioStep step;
	private ApplicationManager appManager;
	private JMenuItem mnuRename;

	/**
	 * Default constructor
	 */
	public ScenarioStepPopup() {
		appManager = ApplicationManager.UNIQUE_INSTANCE;
		initComponent();
	}

	/**
	 * Initialize the component
	 */
	private void initComponent() {

		mnuRename = new JMenuItem("Edit scenario");
		mnuRename.addActionListener(this);
		add(mnuRename);
	}

	/**
	 * Return the scenario step concerned by this popup.
	 * 
	 * @return the scenario-step
	 */
	public ScenarioStep getScenarioStep() {
		return step;
	}

	/**
	 * Sets the scenario concerned by this popup.
	 * 
	 * @param scenario
	 *            the scenario to set
	 */
	public void setScenarioStep(ScenarioStep step) {
		this.step = step;
	}

	/**
	 * Handle action generated by menu.
	 */
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == mnuRename) {
			appManager.editScenarioStep(step);
		}
	}
}
